//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;

namespace FleetManagementServer.Areas.Vehicle.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Device
    {
        public Device()
        {
            VehicleDeviceDetails = new HashSet<VehicleDeviceDetail>();
        }
        public int Id { get; set; }
        public Nullable<int> VehicleDeviceDetailId { get; set; }
        public Guid Guid { get; set; }
        public byte[] SecurityCode { get; set; }
        public bool SecurityCodeVerification { get; set; }
    
        public virtual ICollection<VehicleDeviceDetail> VehicleDeviceDetails { get; set; }
    }
    public static class DeviceBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Device>(builder => { builder.HasData(DeviceSeed.Seed()); });
        }
    }

    public static class DeviceSeed
    {

        public static List<Device> Seed()
        {
            return new List<Device>() { new Device() {Id = 1, Guid = Areas.Device.Data.DeviceSeed.Device1_Guid, SecurityCode = new byte[]{1,2,3,4,5,6,7,8},SecurityCodeVerification = true},
                new Device() {Id=2, Guid = Areas.Device.Data.DeviceSeed.Device2_Guid, SecurityCode = new byte[]{1,2,3,4,5,6,7,8},SecurityCodeVerification = true}};
        }
    }
}
