//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FleetManagementServer.Areas.Vehicle.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Device
    {
        public Device()
        {
            VehicleDeviceDetails = new HashSet<VehicleDeviceDetail>();
        }


        public Guid Id { get; set; }
        public Nullable<int> VehicleDeviceDetailId { get; set; }
        public byte[] SecurityCode { get; set; }
        public bool SecurityCodeVerification { get; set; }
    
        public virtual ICollection<VehicleDeviceDetail> VehicleDeviceDetails { get; set; }
    }
    public static class DeviceBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
            
            modelBuilder.Entity<Device>(builder => {  });
        }
    }

    public static class DeviceSeed
    {

        public static List<Device> Seed()
        {
            return null;
        }
    }
}
