//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;

namespace FleetManagementServer.Areas.Vehicle.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            VehicleDrivers = new HashSet<VehicleDriver>();
        }
        public int Id { get; set; }
        public Nullable<int> VehicleDriverId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
        public string NationalityNumber { get; set; }
        public string LicenseNumber { get; set; }
        public string PhoneNumber { get; set; }

        public virtual ICollection<VehicleDriver> VehicleDrivers { get; set; }
    }
    public static class DriverBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FleetWay>(builder => { builder.HasData(DriverSeed.Seed()); });
        }
    }

    public static class DriverSeed
    {
        public static List<Driver> Seed()
        {
            return new List<Driver>() { new Driver() { Id = 1, BirthDate = DateTime.Parse("1998/10/30"),Name = "asqar", LastName = "jafari", PhoneNumber = "09124272445", NationalityNumber = "007089283848",LicenseNumber = "1234"},
                new Driver() { Id = 2, BirthDate = DateTime.Parse("1995/10/30"),Name = "shahin", LastName = "bahari", PhoneNumber = "09128575442", NationalityNumber = "005045678901",LicenseNumber = "3421"}};
        }
    }
}
