//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Linq;
using FleetManagementServer.Areas.Vehicle.Services;
using Microsoft.EntityFrameworkCore;

namespace FleetManagementServer.Areas.Vehicle.Data
{
    using NetTopologySuite.Geometries;
    using System;
    using System.Collections.Generic;
    
    public partial class FleetWay
    {
        public FleetWay()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int Id { get; set; }

        public string Name { get; set; }
        public LineString Way { get; set; }
    

        public virtual ICollection<Trip> Trips { get; set; }
    }

    public static class FleetWayBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
           // modelBuilder.Entity<FleetWay>(builder => { builder.HasData(FleetWaySeed.Seed()); });
        }
    }
    
    public static class FleetWaySeed
    {
        public static List<FleetWay> Seed()
        {
            var fileStream = File.Open($"{Directory.GetCurrentDirectory()}\\Areas\\Vehicle\\Resources\\FleetWayKml\\BRT4.kml",FileMode.Open,FileAccess.Read);
            var fleetWays = FleetWayHelper.GetFleetWaysFromKml(fileStream).ToList();
            for (var i = 0; i < fleetWays.Count; i++)
            {
                fleetWays[i].Id = i + 1;
            }
            return fleetWays;
        }
    }
}
