//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Linq;
using FleetManagementServer.Areas.Vehicle.Services;
using Microsoft.EntityFrameworkCore;

namespace FleetManagementServer.Areas.Vehicle.Data
{
    using NetTopologySuite.Geometries;
    using System;
    using System.Collections.Generic;
    
    public partial class FleetWay
    {
        public FleetWay()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int Id { get; set; }

        public string Name { get; set; }
        public LineString Way { get; set; }
    

        public virtual ICollection<Trip> Trips { get; set; }
    }

    public static class FleetWayBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FleetWay>(builder => { builder.HasData(FleetWaySeed.Seed()); });
        }
    }
    
    public static class FleetWaySeed
    {
        public static List<FleetWay> Seed()
        {
            var KmlFolder = new DirectoryInfo($"{Directory.GetCurrentDirectory()}\\Areas\\Vehicle\\Resources\\FleetWayKml\\");
            var i = 1;
            List<FleetWay> fleetWays = new List<FleetWay>();
            foreach (var file in KmlFolder.EnumerateFiles())
            {
                var fileStream = file.Open(FileMode.Open, FileAccess.Read);
                var fleetWaysFromKml = FleetWayHelper.GetFleetWaysFromKml(fileStream);
                foreach (var fleetWay in fleetWaysFromKml)
                {
                    fleetWay.Id = i++;
                    fleetWay.Way.SRID = 4326;
                }
                fleetWays.AddRange(fleetWaysFromKml);

            }
            return fleetWays;
        }
    }
}
