//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Linq;
using System.Net.Mime;
using FleetManagementServer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Serialization;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;


namespace FleetManagementServer.Areas.Vehicle.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBrand
    {
        public VehicleBrand()
        {
            Vehicles = new HashSet<Vehicle>();
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
    public static class VehicleBrandBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VehicleBrand>(builder => { builder.HasData(VehicleBrandSeed.Seed()); });
        }
    }

    public static class VehicleBrandSeed
    {
        public static IEnumerable<VehicleBrand> Seed()
        {
            return new VehicleBrand[] {new VehicleBrand() {Id=1, Name = "Benz", Image = ImageHelper.FromFileToByte($"{Directory.GetCurrentDirectory()}\\Areas\\Vehicle\\VehicleBrandImage\\Mercedes - Benz.png") },
                new VehicleBrand() {Id =2, Name = "Renault", Image = ImageHelper.FromFileToByte($"{Directory.GetCurrentDirectory()}\\Areas\\Vehicle\\VehicleBrandImage\\Renault.png") }};
            }
        }
    }
}
