//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FleetManagementServer.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace FleetManagementServer.Areas.Vehicle.Data
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Vehicle
    {
        public Vehicle()
        {
            Devices = new HashSet<VehicleDevice>();
            Drivers = new HashSet<VehicleDriver>();
            Trips = new HashSet<Trip>();
            Locations = new HashSet<FleetLocation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> VehicleBrandId { get; set; }

        public string Code { get; set; }
        public string BodyNumber { get; set; }
        public string MotorNumber { get; set; }
        public string VinNumber { get; set; }
        public byte[] Image { get; set; }

        public virtual ICollection<VehicleDevice> Devices { get; set; }
        public virtual ICollection<VehicleDriver> Drivers { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
        public virtual ICollection<FleetLocation> Locations { get; set; }
        public virtual VehicleType Type { get; set; }
        public virtual VehicleBrand Brand { get; set; }
    }
    public static class VehicleBuilder
    {
        public static void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Device>(builder => { builder.HasData(VehicleSeed.Seed()); });
        }
    }

    public static class VehicleSeed
    {

        public static List<Vehicle> Seed()
        {
            return new List<Vehicle>() { new Vehicle() {Id = 1, VehicleTypeId = 2, Code = "100",BodyNumber = "A12-B15", MotorNumber = "C15-AC21-B", VinNumber = "1234567"},
                new Vehicle() {Id = 2, VehicleTypeId = 2, Code = "104",BodyNumber = "A15-D15", MotorNumber = "C15-AC21-B", VinNumber = "134567"},
                new Vehicle() {Id = 3, VehicleTypeId = 2, Code = "101",BodyNumber = "A16-E15", MotorNumber = "C15-AC21-B", VinNumber = "124567"},
                new Vehicle() {Id = 4, VehicleTypeId = 2, Code = "102",BodyNumber = "A17-D15", MotorNumber = "C15-AC21-B", VinNumber = "123567"},
                new Vehicle() {Id = 5, VehicleTypeId = 2, Code = "103",BodyNumber = "A18-C15", MotorNumber = "C15-AC21-B", VinNumber = "123467"},
            };
        }
    }
}
